-- Initial phrase bank from the "Frases Random de Todos" sheet (rows 6-29),
-- written as Nombre: "Frase". Moderators can replace it from the admin panel.
INSERT INTO phrases (text) VALUES
  ('Gavilan: "Calla vejete"'),
  ('Vivar: "Gavilan anciano"'),
  ('Taringa: "Ayayayai"'),
  ('JP: "Muteados"'),
  ('Gavilan: "Somos 5"'),
  ('Woki: "Habla de su cuy"'),
  ('Woki: "Tiene lag"'),
  ('Pokémon: "Ya fue, bajen pepa"'),
  ('Woki: "Fracasaauuu"'),
  ('Pokémon: "Estornuda kawaii"'),
  ('Vivar: "Pokémon cachudo"'),
  ('Vivar: "Menciona a la prima de cualquiera"'),
  ('Robinson: "Entra y sale del Discord en menos de 5 segundos"'),
  ('JP: "Calla sonso"'),
  ('AXL: "Practicante de mrd"'),
  ('Taringa: "No quiero ir a Roshan"'),
  ('Taringa: "Juega lento"'),
  ('Blue: "Haré stacks"'),
  ('Woki: "Hoy estoy disparando mal"'),
  ('Vivar: "Calla imbécil"'),
  ('Vivar: "Pokémon kachudo"'),
  ('Gavilan: "Ese eres tú"'),
  ('Gavilan: "Váyanse a la mrd, juego solo"'),
  ('Pokémon: "Sr Rotz, yo no le tengo miedo"');
